spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: liuxiaoming_123 #1234
    url: jdbc:mysql://rm-uf6qe0894f7hv8977o.mysql.rds.aliyuncs.com/sell?characterEncoding=utf-8&useSSL=false
    #url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.183
    port: 6379
server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"  #日志格式 日期 - 信息 空格
#  path: /Users/liuxiaoming/Documents/ideawork/sell_log #日志路径 默认名字spring.log
#  file: /Users/liuxiaoming/Documents/ideawork/sell_log/sell.log #日志文件+路径
#  level:  #日志级别
#    com.payease.LoggerTest: debug #日志级别指定某个类 也可以步制定类 直接在level： 后面配置

#日志查看SQL语句
logging:
  level:
    com.payease.dataobject.mapper: trace

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

#projectUrl:
#  wechatMpAuthorize: http://sell.natapp4.cc
#  wechatOpenAuthorize: http://sell.natapp4.cc
#  sell: http://sell.natapp4.cc
projectUrl:
  wechatMpAuthorize: http://127.0.0.1:8080
  wechatOpenAuthorize: http://127.0.0.1:8080
  sell: http://127.0.0.1:8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
